model: lightgbm

preprocessing_parameters:
  fill_missing: True

features: [
  # Raw features
  'OFFICE_ID', 'SIGORTA_TIP', 'SOZLESME_KOKENI', 'KAPSAM_TIPI', 'KAPSAM_GRUBU',
  'POLICE_SEHIR', 'CINSIYET', 'MEMLEKET', 'MESLEK', 'MESLEK_KIRILIM',
  'MUSTERI_SEGMENTI', 'YATIRIM_KARAKTERI', 'MEDENI_HAL',
  'EGITIM_DURUM',# 'GELIR', 'COCUK_SAYISI',
  # Payment features
  'ODENEN_TUTAR_STD', 'VADE_TUTARI_STD', 'ODENMEYEN_AYLAR', 'SENE_HESAP_DEGERI_ORANI',
  'PAYMENT_AMOUNT_PCA_COMPONENT_0', 'PAYMENT_AMOUNT_PCA_COMPONENT_1',
  'PAID_AMOUNT_PCA_COMPONENT_0', 'PAID_AMOUNT_PCA_COMPONENT_1', 'PAID_AMOUNT_PCA_COMPONENT_2',
  'UNPAID_AMOUNT_PCA_COMPONENT_0', 'UNPAID_AMOUNT_PCA_COMPONENT_1', 'UNPAID_AMOUNT_PCA_COMPONENT_2',
  'PAID_AMOUNT_RATIO_PCA_COMPONENT_0', 'PAID_AMOUNT_RATIO_PCA_COMPONENT_1', 'PAID_AMOUNT_RATIO_PCA_COMPONENT_2',
  # Date and time features
  'SOZLESME_TOPLAM_AY', 'YAS',
  # Categorical feature combinations
  'USER_ID1.1',
  # Frequency encoded categorical features
  'POLICE_SEHIR_FREQUENCY',
  # Aggregation features
  'OFFICE_ID_ARALIK_ODENEN_TUTAR_STD',
  'MUSTERI_SEGMENTI_ARALIK_ODENEN_TUTAR_MEAN', 'MUSTERI_SEGMENTI_ARALIK_ODENMEYEN_TUTAR_STD',
  'MUSTERI_SEGMENTI_ARALIK_ODENEN_TUTAR_MAX', 'MUSTERI_SEGMENTI_ARALIK_ODENEN_TUTAR_MIN',
  'MUSTERI_SEGMENTI_ARALIK_ODENEN_TUTAR_ORANI_MEAN', 'MUSTERI_SEGMENTI_ARALIK_ODENEN_TUTAR_ORANI_STD',
  'EGITIM_DURUM_ARALIK_ODENEN_TUTAR_STD', 'MEDENI_HAL_ARALIK_ODENEN_TUTAR_ORANI_STD', 'YATIRIM_KARAKTERI_ARALIK_ODENMEYEN_TUTAR_STD',
]
target: 'ARTIS_DURUMU'
categorical_features: []

model_parameters:
  num_leaves: 512
  learning_rate: 0.005
  bagging_fraction: 0.9
  bagging_freq: 1
  feature_fraction: 0.7
  feature_fraction_bynode: 0.9
  min_data_in_leaf: 1
  min_gain_to_split: 0.00001
  lambda_l1: 0
  lambda_l2: 0.0001
  max_bin: 255
  max_depth: -1
  objective: binary
  scale_pos_weight: 1.0
  seed: 42
  feature_fraction_seed: 42
  bagging_seed: 42
  drop_seed: 42
  data_random_seed: 42
  boosting_type: gbdt
  verbose: 1
  metric: auc
  n_jobs: -1

fit_parameters:
  boosting_rounds: 10000
  early_stopping_rounds: 250
  verbose_eval: 250

sampler_class: null
sampler_parameters: {}
